### ISSUE TITLE
Upload more python stuff

### ISSUE THREAD

**Issue by ohnx** [mebsim/Periodic-Table.py#1]
Upload your shooter, too! :D

**Comment by mebsim** [comment]
I might, but I want to work on it a bit more. There is a problem with the clicking of the buttons which is annoying me.

**Comment by mebsim** [comment]
I'm going to in late June, I just have to finish something else, then I can work on it. By June I should be able to upload it.

**Comment by mebsim** [comment]
Check out the thing I started in the other organization

**Comment by mebsim** [comment]
I think I can get it up by June 16.
